#ifndef STRUCTURAL_PATTERNS_SP_GLOBALS_H
#define STRUCTURAL_PATTERNS_SP_GLOBALS_H

enum DecompositionStrategy {
    FORKS_ONLY,
    INVERTED_FORKS_ONLY,
    BOTH_FORKS_AND_INVERTED_FORKS,
    SEMIFORKS_ONLY,
    HOURGLASSES_ONLY,
    MAX_DECOMPOSITION_STRATEGY
};

enum CostPartitioning {
    UNIFORM,
    ENSEMBLE_UNIFORM,
    OPTIMAL,
    INITIAL_OPTIMAL,
    GREEDY_SAMPLE,
    POST_HOC_OPTIMIZATION,
    MAX_COST_PARTITIONING
};

enum SingletonStrategy{
    NECESSARY,
    BY_DEFINITION,
    COMPENSATE_FOR_DOMAIN_DECOMPOSITION,
    MAX_SINGLETON_STRATEGY
};

enum VariablesSelectionStrategy {
    LANDMARK_VARIABLES_ONLY,
    NON_LANDMARK_VARIABLES_ONLY,
    ALL_VARIABLES,
    MIXED_LANDMARK_FORKS_NON_LANDMARK_INVERTED_FORKS,
    MIXED_NON_LANDMARK_FORKS_LANDMARK_INVERTED_FORKS,
    MAX_ENSEMBLE_STRATEGY
};


enum LandmarkEnrichmentStrategy {
    VARIABLE_PER_LANDMARK_NO_INIT,
    VARIABLE_PER_LANDMARK,
    LANDMARK_PATHS_LINKS_COVERING_VARIABLES,
    LANDMARK_PATHS_NODES_COVERING_VARIABLES,
    SINGLE_GOAL,
    ALL_LANDMARK_PATHS_VARIABLES,
    MAX_LANDMARK_ENRICHMENT_STRATEGY
};



enum AbstractionType {
    FORK,
    INVERTED_FORK,
    PATTERN,
    SEMIFORK,
    HOURGLASS,
    MAX_ABSTRACTION_TYPE
};

enum AbstractionCreationStatus {
    NONE,
    PARTIAL,
    DONE,
    MAX_CREATION_STATUS
};


extern int LP_INFINITY;
extern int MAX_LP_SIZE;
extern double LP_MAX_TIME_BOUND;
extern int MAX_NUM_PATHS;
#define IFORKDOMBOUND 3

extern double infinity;
int compare (const void * a, const void * b);

#endif
